# Generated by Django 4.2.2 on 2025-10-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': [('can_unpublish_product', 'может отменять публикацию продукта')], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
